extern void __RegisterClass__Editor__AnimationAddKeysAction();
extern void __RegisterClass__Editor__AnimationDeleteKeysAction();
extern void __RegisterClass__Editor__AnimationKeysChangeAction();
extern void __RegisterClass__Editor__AnimationWindow();
extern void __RegisterClass__Editor__CurvesSheet();
extern void __RegisterClass__Editor__KeyHandlesSheet();
extern void __RegisterClass__Editor__AnimationPropertiesTree();
extern void __RegisterClass__Editor__AnimationPropertiesTreeNode();
extern void __RegisterClass__Editor__AnimationTimeline();
extern void __RegisterClass__Editor__AnimationKeyDragHandle();
extern void __RegisterClass__Editor__ITrackControl();
extern void __RegisterClass__Editor__MapKeyFramesTrackControl();
extern void __RegisterClass__Editor__Vec2KeyFramesTrackControl();
extern void __RegisterClass__Editor__AnimationTree();
extern void __RegisterClass__Editor__AnimationTreeNode();
extern void __RegisterClass__Editor__AssetIcon();
extern void __RegisterClass__Editor__AssetsIconsScrollArea();
extern void __RegisterClass__Editor__AssetsWindow();
extern void __RegisterClass__Editor__AssetsFoldersTree();
extern void __RegisterClass__Editor__FoldersTree();
extern void __RegisterClass__Editor__CreateAction();
extern void __RegisterClass__Editor__DeleteAction();
extern void __RegisterClass__Editor__DeleteAction__ObjectInfo();
extern void __RegisterClass__Editor__EnableAction();
extern void __RegisterClass__Editor__IAction();
extern void __RegisterClass__Editor__LockAction();
extern void __RegisterClass__Editor__PropertyChangeAction();
extern void __RegisterClass__Editor__ReparentAction();
extern void __RegisterClass__Editor__SelectAction();
extern void __RegisterClass__Editor__TransformAction();
extern void __RegisterClass__Editor__EditorConfig();
extern void __RegisterClass__Editor__EditorConfig__GlobalConfig();
extern void __RegisterClass__Editor__EditorConfig__ProjectConfig();
extern void __RegisterClass__Editor__ActorProperty();
extern void __RegisterClass__Editor__AssetProperty();
extern void __RegisterClass__Editor__BooleanProperty();
extern void __RegisterClass__Editor__BorderFProperty();
extern void __RegisterClass__Editor__BorderIProperty();
extern void __RegisterClass__Editor__ColorGradientProperty();
extern void __RegisterClass__Editor__ColorProperty();
extern void __RegisterClass__Editor__ComponentProperty();
extern void __RegisterClass__Editor__CurveProperty();
extern void __RegisterClass__Editor__EnumProperty();
extern void __RegisterClass__Editor__FloatProperty();
extern void __RegisterClass__Editor__FunctionProperty();
extern void __RegisterClass__Editor__IntegerProperty();
extern void __RegisterClass__Editor__ObjectProperty();
extern void __RegisterClass__Editor__ObjectPtrProperty();
extern void __RegisterClass__Editor__RectFProperty();
extern void __RegisterClass__Editor__RectIProperty();
extern void __RegisterClass__Editor__SceneLayerRefProperty();
extern void __RegisterClass__Editor__SceneLayersListProperty();
extern void __RegisterClass__Editor__ScriptValueProperty();
extern void __RegisterClass__Editor__StringProperty();
extern void __RegisterClass__Editor__TagsProperty();
extern void __RegisterClass__Editor__Vec2FProperty();
extern void __RegisterClass__Editor__Vec2IProperty();
extern void __RegisterClass__Editor__VectorProperty();
extern void __RegisterClass__Editor__WStringProperty();
extern void __RegisterClass__Editor__IObjectPropertiesViewer();
extern void __RegisterClass__Editor__IPropertyField();
extern void __RegisterClass__Editor__ObjectViewer();
extern void __RegisterClass__Editor__AnimationViewer();
extern void __RegisterClass__Editor__ImageAssetViewer();
extern void __RegisterClass__Editor__VectorFontAssetViewer();
extern void __RegisterClass__Editor__CameraActorViewer();
extern void __RegisterClass__Editor__AnimationStateViewer();
extern void __RegisterClass__Editor__MeshComponentViewer();
extern void __RegisterClass__Editor__SkinningMeshBoneComponentViewer();
extern void __RegisterClass__Editor__SkinningMeshComponentViewer();
extern void __RegisterClass__Editor__DefaultObjectPropertiesViewer();
extern void __RegisterClass__Editor__SpriteViewer();
extern void __RegisterClass__Editor__TextViewer();
extern void __RegisterClass__Editor__CustomFrameTool();
extern void __RegisterClass__Editor__FrameTool();
extern void __RegisterClass__Editor__IEditTool();
extern void __RegisterClass__Editor__MeshTopologyTool();
extern void __RegisterClass__Editor__MeshWeightsTool();
extern void __RegisterClass__Editor__MoveTool();
extern void __RegisterClass__Editor__RotateTool();
extern void __RegisterClass__Editor__ScaleTool();
extern void __RegisterClass__Editor__SelectionTool();
extern void __RegisterClass__Editor__SkeletonTool();
extern void __RegisterClass__Editor__SplineTool();
extern void __RegisterClass__o2__BasicUIStyleBuilder();
extern void __RegisterClass__Editor__EditorUIStyleBuilder();
extern void __RegisterClass__Editor__CurveAddKeysAction();
extern void __RegisterClass__Editor__CurveDeleteKeysAction();
extern void __RegisterClass__Editor__CurveKeysChangeAction();
extern void __RegisterClass__Editor__CurvesEditor();
extern void __RegisterClass__Editor__CurvesEditor__CurveHandle();
extern void __RegisterClass__Editor__CurvesEditor__CurveCopyInfo();
extern void __RegisterClass__Editor__CurvePreview();
extern void __RegisterClass__Editor__FrameScrollView();
extern void __RegisterClass__Editor__ImageSlicesEditorWidget();
extern void __RegisterClass__Editor__ImageSlicesEditorWidget__PreviewImage();
extern void __RegisterClass__Editor__ScrollView();
extern void __RegisterClass__Editor__SpoilerWithHead();
extern void __RegisterClass__Editor__TexturePreview();
extern void __RegisterClass__Editor__DockWindowPlace();
extern void __RegisterClass__Editor__DockableWindow();
extern void __RegisterClass__Editor__IEditorWindow();
extern void __RegisterClass__Editor__WindowsLayout();
extern void __RegisterClass__Editor__WindowsLayout__WindowDockPlaceInfo();
extern void __RegisterClass__Editor__GameWindow();
extern void __RegisterClass__Editor__GameWindow__GameView();
extern void __RegisterClass__Editor__GameWindow__SimulationDevice();
extern void __RegisterClass__Editor__LogWindow();
extern void __RegisterClass__Editor__ActorViewer();
extern void __RegisterClass__Editor__AddComponentPanel();
extern void __RegisterClass__Editor__ComponentsTree();
extern void __RegisterClass__Editor__ComponentsTreeNode();
extern void __RegisterClass__Editor__DefaultActorComponentViewer();
extern void __RegisterClass__Editor__DefaultActorHeaderViewer();
extern void __RegisterClass__Editor__DefaultActorPropertiesViewer();
extern void __RegisterClass__Editor__DefaultActorTransformViewer();
extern void __RegisterClass__Editor__IActorComponentViewer();
extern void __RegisterClass__Editor__IActorHeaderViewer();
extern void __RegisterClass__Editor__IActorPropertiesViewer();
extern void __RegisterClass__Editor__IActorTransformViewer();
extern void __RegisterClass__Editor__AssetPropertiesViewer();
extern void __RegisterClass__Editor__DefaultPropertiesViewer();
extern void __RegisterClass__Editor__IPropertiesViewer();
extern void __RegisterClass__Editor__PropertiesWindow();
extern void __RegisterClass__Editor__DefaultWidgetLayerHeaderViewer();
extern void __RegisterClass__Editor__DefaultWidgetLayerLayoutViewer();
extern void __RegisterClass__Editor__DefaultWidgetLayerPropertiesViewer();
extern void __RegisterClass__Editor__IWidgetLayerHeaderViewer();
extern void __RegisterClass__Editor__IWidgetLayerLayoutViewer();
extern void __RegisterClass__Editor__IWidgetLayerPropertiesViewer();
extern void __RegisterClass__Editor__WidgetLayerViewer();
extern void __RegisterClass__Editor__LayersPopup();
extern void __RegisterClass__Editor__LayerPopupItem();
extern void __RegisterClass__Editor__SceneDragHandle();
extern void __RegisterClass__Editor__SceneEditScreen();
extern void __RegisterClass__Editor__SceneWindow();
extern void __RegisterClass__Editor__DrawOrderTree();
extern void __RegisterClass__Editor__DrawOrderTreeNode();
extern void __RegisterClass__Editor__SceneHierarchyTree();
extern void __RegisterClass__Editor__SceneHierarchyTreeNode();
extern void __RegisterClass__Editor__TreeWindow();


extern void InitializeTypeso2Editor()
{
    __RegisterClass__Editor__AnimationAddKeysAction();
    __RegisterClass__Editor__AnimationDeleteKeysAction();
    __RegisterClass__Editor__AnimationKeysChangeAction();
    __RegisterClass__Editor__AnimationWindow();
    __RegisterClass__Editor__CurvesSheet();
    __RegisterClass__Editor__KeyHandlesSheet();
    __RegisterClass__Editor__AnimationPropertiesTree();
    __RegisterClass__Editor__AnimationPropertiesTreeNode();
    __RegisterClass__Editor__AnimationTimeline();
    __RegisterClass__Editor__AnimationKeyDragHandle();
    __RegisterClass__Editor__ITrackControl();
    __RegisterClass__Editor__MapKeyFramesTrackControl();
    __RegisterClass__Editor__Vec2KeyFramesTrackControl();
    __RegisterClass__Editor__AnimationTree();
    __RegisterClass__Editor__AnimationTreeNode();
    __RegisterClass__Editor__AssetIcon();
    __RegisterClass__Editor__AssetsIconsScrollArea();
    __RegisterClass__Editor__AssetsWindow();
    __RegisterClass__Editor__AssetsFoldersTree();
    __RegisterClass__Editor__FoldersTree();
    __RegisterClass__Editor__CreateAction();
    __RegisterClass__Editor__DeleteAction();
    __RegisterClass__Editor__DeleteAction__ObjectInfo();
    __RegisterClass__Editor__EnableAction();
    __RegisterClass__Editor__IAction();
    __RegisterClass__Editor__LockAction();
    __RegisterClass__Editor__PropertyChangeAction();
    __RegisterClass__Editor__ReparentAction();
    __RegisterClass__Editor__SelectAction();
    __RegisterClass__Editor__TransformAction();
    __RegisterClass__Editor__EditorConfig();
    __RegisterClass__Editor__EditorConfig__GlobalConfig();
    __RegisterClass__Editor__EditorConfig__ProjectConfig();
    __RegisterClass__Editor__ActorProperty();
    __RegisterClass__Editor__AssetProperty();
    __RegisterClass__Editor__BooleanProperty();
    __RegisterClass__Editor__BorderFProperty();
    __RegisterClass__Editor__BorderIProperty();
    __RegisterClass__Editor__ColorGradientProperty();
    __RegisterClass__Editor__ColorProperty();
    __RegisterClass__Editor__ComponentProperty();
    __RegisterClass__Editor__CurveProperty();
    __RegisterClass__Editor__EnumProperty();
    __RegisterClass__Editor__FloatProperty();
    __RegisterClass__Editor__FunctionProperty();
    __RegisterClass__Editor__IntegerProperty();
    __RegisterClass__Editor__ObjectProperty();
    __RegisterClass__Editor__ObjectPtrProperty();
    __RegisterClass__Editor__RectFProperty();
    __RegisterClass__Editor__RectIProperty();
    __RegisterClass__Editor__SceneLayerRefProperty();
    __RegisterClass__Editor__SceneLayersListProperty();
    __RegisterClass__Editor__ScriptValueProperty();
    __RegisterClass__Editor__StringProperty();
    __RegisterClass__Editor__TagsProperty();
    __RegisterClass__Editor__Vec2FProperty();
    __RegisterClass__Editor__Vec2IProperty();
    __RegisterClass__Editor__VectorProperty();
    __RegisterClass__Editor__WStringProperty();
    __RegisterClass__Editor__IObjectPropertiesViewer();
    __RegisterClass__Editor__IPropertyField();
    __RegisterClass__Editor__ObjectViewer();
    __RegisterClass__Editor__AnimationViewer();
    __RegisterClass__Editor__ImageAssetViewer();
    __RegisterClass__Editor__VectorFontAssetViewer();
    __RegisterClass__Editor__CameraActorViewer();
    __RegisterClass__Editor__AnimationStateViewer();
    __RegisterClass__Editor__MeshComponentViewer();
    __RegisterClass__Editor__SkinningMeshBoneComponentViewer();
    __RegisterClass__Editor__SkinningMeshComponentViewer();
    __RegisterClass__Editor__DefaultObjectPropertiesViewer();
    __RegisterClass__Editor__SpriteViewer();
    __RegisterClass__Editor__TextViewer();
    __RegisterClass__Editor__CustomFrameTool();
    __RegisterClass__Editor__FrameTool();
    __RegisterClass__Editor__IEditTool();
    __RegisterClass__Editor__MeshTopologyTool();
    __RegisterClass__Editor__MeshWeightsTool();
    __RegisterClass__Editor__MoveTool();
    __RegisterClass__Editor__RotateTool();
    __RegisterClass__Editor__ScaleTool();
    __RegisterClass__Editor__SelectionTool();
    __RegisterClass__Editor__SkeletonTool();
    __RegisterClass__Editor__SplineTool();
    __RegisterClass__o2__BasicUIStyleBuilder();
    __RegisterClass__Editor__EditorUIStyleBuilder();
    __RegisterClass__Editor__CurveAddKeysAction();
    __RegisterClass__Editor__CurveDeleteKeysAction();
    __RegisterClass__Editor__CurveKeysChangeAction();
    __RegisterClass__Editor__CurvesEditor();
    __RegisterClass__Editor__CurvesEditor__CurveHandle();
    __RegisterClass__Editor__CurvesEditor__CurveCopyInfo();
    __RegisterClass__Editor__CurvePreview();
    __RegisterClass__Editor__FrameScrollView();
    __RegisterClass__Editor__ImageSlicesEditorWidget();
    __RegisterClass__Editor__ImageSlicesEditorWidget__PreviewImage();
    __RegisterClass__Editor__ScrollView();
    __RegisterClass__Editor__SpoilerWithHead();
    __RegisterClass__Editor__TexturePreview();
    __RegisterClass__Editor__DockWindowPlace();
    __RegisterClass__Editor__DockableWindow();
    __RegisterClass__Editor__IEditorWindow();
    __RegisterClass__Editor__WindowsLayout();
    __RegisterClass__Editor__WindowsLayout__WindowDockPlaceInfo();
    __RegisterClass__Editor__GameWindow();
    __RegisterClass__Editor__GameWindow__GameView();
    __RegisterClass__Editor__GameWindow__SimulationDevice();
    __RegisterClass__Editor__LogWindow();
    __RegisterClass__Editor__ActorViewer();
    __RegisterClass__Editor__AddComponentPanel();
    __RegisterClass__Editor__ComponentsTree();
    __RegisterClass__Editor__ComponentsTreeNode();
    __RegisterClass__Editor__DefaultActorComponentViewer();
    __RegisterClass__Editor__DefaultActorHeaderViewer();
    __RegisterClass__Editor__DefaultActorPropertiesViewer();
    __RegisterClass__Editor__DefaultActorTransformViewer();
    __RegisterClass__Editor__IActorComponentViewer();
    __RegisterClass__Editor__IActorHeaderViewer();
    __RegisterClass__Editor__IActorPropertiesViewer();
    __RegisterClass__Editor__IActorTransformViewer();
    __RegisterClass__Editor__AssetPropertiesViewer();
    __RegisterClass__Editor__DefaultPropertiesViewer();
    __RegisterClass__Editor__IPropertiesViewer();
    __RegisterClass__Editor__PropertiesWindow();
    __RegisterClass__Editor__DefaultWidgetLayerHeaderViewer();
    __RegisterClass__Editor__DefaultWidgetLayerLayoutViewer();
    __RegisterClass__Editor__DefaultWidgetLayerPropertiesViewer();
    __RegisterClass__Editor__IWidgetLayerHeaderViewer();
    __RegisterClass__Editor__IWidgetLayerLayoutViewer();
    __RegisterClass__Editor__IWidgetLayerPropertiesViewer();
    __RegisterClass__Editor__WidgetLayerViewer();
    __RegisterClass__Editor__LayersPopup();
    __RegisterClass__Editor__LayerPopupItem();
    __RegisterClass__Editor__SceneDragHandle();
    __RegisterClass__Editor__SceneEditScreen();
    __RegisterClass__Editor__SceneWindow();
    __RegisterClass__Editor__DrawOrderTree();
    __RegisterClass__Editor__DrawOrderTreeNode();
    __RegisterClass__Editor__SceneHierarchyTree();
    __RegisterClass__Editor__SceneHierarchyTreeNode();
    __RegisterClass__Editor__TreeWindow();
}