extern void __RegisterClass__o2__AnimationClip();
extern void __RegisterClass__o2__AnimationMask();
extern void __RegisterClass__o2__AnimationPlayer();
extern void __RegisterClass__o2__AnimationState();
extern void __RegisterClass__o2__IAnimation();
extern void __RegisterClass__o2__AnimationTrack_o2__Color4_();
extern void __RegisterClass__o2__AnimationTrack_o2__Color4___Player();
extern void __RegisterClass__o2__AnimationTrack_o2__Color4___Key();
extern void __RegisterClass__o2__AnimationTrack_float_();
extern void __RegisterClass__o2__AnimationTrack_float___Player();
extern void __RegisterClass__o2__AnimationTrack_o2__Vec2F_();
extern void __RegisterClass__o2__AnimationTrack_o2__Vec2F___Player();
extern void __RegisterClass__o2__IAnimationTrack();
extern void __RegisterClass__o2__IAnimationTrack__IPlayer();
extern void __RegisterClass__o2__Application();
extern void __RegisterClass__o2__Asset();
extern void __RegisterClass__o2__AssetInfo();
extern void __RegisterClass__o2__BaseAssetRef();
extern void __RegisterClass__o2__AssetsTree();
extern void __RegisterClass__o2__AssetMeta();
extern void __RegisterClass__o2__ActorAsset();
extern void __RegisterClass__o2__AnimationAsset();
extern void __RegisterClass__o2__AtlasAsset();
extern void __RegisterClass__o2__AtlasAsset__PlatformMeta();
extern void __RegisterClass__o2__AtlasAsset__Meta();
extern void __RegisterClass__o2__AtlasAsset__Page();
extern void __RegisterClass__o2__BinaryAsset();
extern void __RegisterClass__o2__BitmapFontAsset();
extern void __RegisterClass__o2__BitmapFontAsset__Meta();
extern void __RegisterClass__o2__DataAsset();
extern void __RegisterClass__o2__FolderAsset();
extern void __RegisterClass__o2__FontAsset();
extern void __RegisterClass__o2__ImageAsset();
extern void __RegisterClass__o2__ImageAsset__PlatformMeta();
extern void __RegisterClass__o2__ImageAsset__Meta();
extern void __RegisterClass__o2__JavaScriptAsset();
extern void __RegisterClass__o2__SceneAsset();
extern void __RegisterClass__o2__VectorFontAsset();
extern void __RegisterClass__o2__VectorFontAsset__Meta();
extern void __RegisterClass__o2__PhysicsConfig();
extern void __RegisterClass__o2__ProjectConfig();
extern void __RegisterClass__o2__Camera();
extern void __RegisterClass__o2__ParticleSource();
extern void __RegisterClass__o2__SingleSpriteParticleSource();
extern void __RegisterClass__o2__MultiSpriteParticleSource();
extern void __RegisterClass__o2__ParticlesEffect();
extern void __RegisterClass__o2__ParticlesGravityEffect();
extern void __RegisterClass__o2__ParticlesColorEffect();
extern void __RegisterClass__o2__ParticlesRandomColorEffect();
extern void __RegisterClass__o2__ParticlesSizeEffect();
extern void __RegisterClass__o2__ParticlesAngleEffect();
extern void __RegisterClass__o2__ParticlesAngleSpeedEffect();
extern void __RegisterClass__o2__ParticlesVelocityEffect();
extern void __RegisterClass__o2__ParticlesSplineEffect();
extern void __RegisterClass__o2__ParticlesEmitter();
extern void __RegisterClass__o2__ParticlesEmitterShape();
extern void __RegisterClass__o2__CircleParticlesEmitterShape();
extern void __RegisterClass__o2__SquareParticlesEmitterShape();
extern void __RegisterClass__o2__IRectDrawable();
extern void __RegisterClass__o2__FunctionalRectDrawable();
extern void __RegisterClass__o2__Sprite();
extern void __RegisterClass__o2__Text();
extern void __RegisterClass__o2__TextureRef();
extern void __RegisterClass__o2__VectorFont__Effect();
extern void __RegisterClass__o2__FontStrokeEffect();
extern void __RegisterClass__o2__FontGradientEffect();
extern void __RegisterClass__o2__FontColorEffect();
extern void __RegisterClass__o2__FontShadowEffect();
extern void __RegisterClass__o2__Actor();
extern void __RegisterClass__o2__BaseActorLinkRef();
extern void __RegisterClass__o2__ActorTransform();
extern void __RegisterClass__o2__ActorTransformData();
extern void __RegisterClass__o2__CameraActor();
extern void __RegisterClass__o2__Component();
extern void __RegisterClass__o2__BaseComponentLinkRef();
extern void __RegisterClass__o2__AnimationComponent();
extern void __RegisterClass__o2__EditorTestComponent();
extern void __RegisterClass__o2__EditorTestComponent__TestInside();
extern void __RegisterClass__o2__EditorTestComponent__TestDerivedInside();
extern void __RegisterClass__o2__ImageComponent();
extern void __RegisterClass__o2__MeshComponent();
extern void __RegisterClass__o2__ParticlesEmitterComponent();
extern void __RegisterClass__o2__ScissorClippingComponent();
extern void __RegisterClass__o2__ScriptableComponent();
extern void __RegisterClass__o2__SkinningMeshBoneComponent();
extern void __RegisterClass__o2__SkinningMeshComponent();
extern void __RegisterClass__o2__DrawableComponent();
extern void __RegisterClass__o2__ISceneDrawable();
extern void __RegisterClass__o2__BoxCollider();
extern void __RegisterClass__o2__CircleCollider();
extern void __RegisterClass__o2__ICollider();
extern void __RegisterClass__o2__RigidBody();
extern void __RegisterClass__o2__Scene();
extern void __RegisterClass__o2__SceneLayer();
extern void __RegisterClass__o2__SceneLayersList();
extern void __RegisterClass__o2__Tag();
extern void __RegisterClass__o2__TagGroup();
extern void __RegisterClass__o2__Widget();
extern void __RegisterClass__o2__Widget__LayersEditable();
extern void __RegisterClass__o2__Widget__InternalChildrenEditableEditable();
extern void __RegisterClass__o2__WidgetLayer();
extern void __RegisterClass__o2__WidgetLayerLayout();
extern void __RegisterClass__o2__WidgetLayout();
extern void __RegisterClass__o2__WidgetLayoutData();
extern void __RegisterClass__o2__WidgetState();
extern void __RegisterClass__o2__Button();
extern void __RegisterClass__o2__ContextMenu();
extern void __RegisterClass__o2__ContextMenuItem();
extern void __RegisterClass__o2__ContextMenu__Item();
extern void __RegisterClass__o2__CustomDropDown();
extern void __RegisterClass__o2__CustomList();
extern void __RegisterClass__o2__DropDown();
extern void __RegisterClass__o2__EditBox();
extern void __RegisterClass__o2__GridLayout();
extern void __RegisterClass__o2__GridLayoutScrollArea();
extern void __RegisterClass__o2__HorizontalLayout();
extern void __RegisterClass__o2__HorizontalProgress();
extern void __RegisterClass__o2__HorizontalScrollBar();
extern void __RegisterClass__o2__Image();
extern void __RegisterClass__o2__Label();
extern void __RegisterClass__o2__List();
extern void __RegisterClass__o2__LongList();
extern void __RegisterClass__o2__MenuPanel();
extern void __RegisterClass__o2__MenuPanel__Item();
extern void __RegisterClass__o2__PopupWidget();
extern void __RegisterClass__o2__ScrollArea();
extern void __RegisterClass__o2__Spoiler();
extern void __RegisterClass__o2__Toggle();
extern void __RegisterClass__o2__Tree();
extern void __RegisterClass__o2__TreeNode();
extern void __RegisterClass__o2__VerticalLayout();
extern void __RegisterClass__o2__VerticalProgress();
extern void __RegisterClass__o2__VerticalScrollBar();
extern void __RegisterClass__o2__Window();
extern void __RegisterClass__o2__DragHandle();
extern void __RegisterClass__o2__WidgetDragHandle();
extern void __RegisterClass__o2__SceneEditableObject();
extern void __RegisterClass__o2__ColorGradient();
extern void __RegisterClass__o2__ColorGradient__Key();
extern void __RegisterClass__o2__Curve();
extern void __RegisterClass__o2__Curve__Key();
extern void __RegisterClass__o2__Layout();
extern void __RegisterClass__o2__Spline();
extern void __RegisterClass__o2__Spline__Key();
extern void __RegisterClass__o2__Transform();
extern void __RegisterClass__o2__ISerializable();
extern void __RegisterClass__o2__ShortcutKeys();
extern void __RegisterClass__o2__TimeStamp();


extern void InitializeTypeso2Framework()
{
    __RegisterClass__o2__AnimationClip();
    __RegisterClass__o2__AnimationMask();
    __RegisterClass__o2__AnimationPlayer();
    __RegisterClass__o2__AnimationState();
    __RegisterClass__o2__IAnimation();
    __RegisterClass__o2__AnimationTrack_o2__Color4_();
    __RegisterClass__o2__AnimationTrack_o2__Color4___Player();
    __RegisterClass__o2__AnimationTrack_o2__Color4___Key();
    __RegisterClass__o2__AnimationTrack_float_();
    __RegisterClass__o2__AnimationTrack_float___Player();
    __RegisterClass__o2__AnimationTrack_o2__Vec2F_();
    __RegisterClass__o2__AnimationTrack_o2__Vec2F___Player();
    __RegisterClass__o2__IAnimationTrack();
    __RegisterClass__o2__IAnimationTrack__IPlayer();
    __RegisterClass__o2__Application();
    __RegisterClass__o2__Asset();
    __RegisterClass__o2__AssetInfo();
    __RegisterClass__o2__BaseAssetRef();
    __RegisterClass__o2__AssetsTree();
    __RegisterClass__o2__AssetMeta();
    __RegisterClass__o2__ActorAsset();
    __RegisterClass__o2__AnimationAsset();
    __RegisterClass__o2__AtlasAsset();
    __RegisterClass__o2__AtlasAsset__PlatformMeta();
    __RegisterClass__o2__AtlasAsset__Meta();
    __RegisterClass__o2__AtlasAsset__Page();
    __RegisterClass__o2__BinaryAsset();
    __RegisterClass__o2__BitmapFontAsset();
    __RegisterClass__o2__BitmapFontAsset__Meta();
    __RegisterClass__o2__DataAsset();
    __RegisterClass__o2__FolderAsset();
    __RegisterClass__o2__FontAsset();
    __RegisterClass__o2__ImageAsset();
    __RegisterClass__o2__ImageAsset__PlatformMeta();
    __RegisterClass__o2__ImageAsset__Meta();
    __RegisterClass__o2__JavaScriptAsset();
    __RegisterClass__o2__SceneAsset();
    __RegisterClass__o2__VectorFontAsset();
    __RegisterClass__o2__VectorFontAsset__Meta();
    __RegisterClass__o2__PhysicsConfig();
    __RegisterClass__o2__ProjectConfig();
    __RegisterClass__o2__Camera();
    __RegisterClass__o2__ParticleSource();
    __RegisterClass__o2__SingleSpriteParticleSource();
    __RegisterClass__o2__MultiSpriteParticleSource();
    __RegisterClass__o2__ParticlesEffect();
    __RegisterClass__o2__ParticlesGravityEffect();
    __RegisterClass__o2__ParticlesColorEffect();
    __RegisterClass__o2__ParticlesRandomColorEffect();
    __RegisterClass__o2__ParticlesSizeEffect();
    __RegisterClass__o2__ParticlesAngleEffect();
    __RegisterClass__o2__ParticlesAngleSpeedEffect();
    __RegisterClass__o2__ParticlesVelocityEffect();
    __RegisterClass__o2__ParticlesSplineEffect();
    __RegisterClass__o2__ParticlesEmitter();
    __RegisterClass__o2__ParticlesEmitterShape();
    __RegisterClass__o2__CircleParticlesEmitterShape();
    __RegisterClass__o2__SquareParticlesEmitterShape();
    __RegisterClass__o2__IRectDrawable();
    __RegisterClass__o2__FunctionalRectDrawable();
    __RegisterClass__o2__Sprite();
    __RegisterClass__o2__Text();
    __RegisterClass__o2__TextureRef();
    __RegisterClass__o2__VectorFont__Effect();
    __RegisterClass__o2__FontStrokeEffect();
    __RegisterClass__o2__FontGradientEffect();
    __RegisterClass__o2__FontColorEffect();
    __RegisterClass__o2__FontShadowEffect();
    __RegisterClass__o2__Actor();
    __RegisterClass__o2__BaseActorLinkRef();
    __RegisterClass__o2__ActorTransform();
    __RegisterClass__o2__ActorTransformData();
    __RegisterClass__o2__CameraActor();
    __RegisterClass__o2__Component();
    __RegisterClass__o2__BaseComponentLinkRef();
    __RegisterClass__o2__AnimationComponent();
    __RegisterClass__o2__EditorTestComponent();
    __RegisterClass__o2__EditorTestComponent__TestInside();
    __RegisterClass__o2__EditorTestComponent__TestDerivedInside();
    __RegisterClass__o2__ImageComponent();
    __RegisterClass__o2__MeshComponent();
    __RegisterClass__o2__ParticlesEmitterComponent();
    __RegisterClass__o2__ScissorClippingComponent();
    __RegisterClass__o2__ScriptableComponent();
    __RegisterClass__o2__SkinningMeshBoneComponent();
    __RegisterClass__o2__SkinningMeshComponent();
    __RegisterClass__o2__DrawableComponent();
    __RegisterClass__o2__ISceneDrawable();
    __RegisterClass__o2__BoxCollider();
    __RegisterClass__o2__CircleCollider();
    __RegisterClass__o2__ICollider();
    __RegisterClass__o2__RigidBody();
    __RegisterClass__o2__Scene();
    __RegisterClass__o2__SceneLayer();
    __RegisterClass__o2__SceneLayersList();
    __RegisterClass__o2__Tag();
    __RegisterClass__o2__TagGroup();
    __RegisterClass__o2__Widget();
    __RegisterClass__o2__Widget__LayersEditable();
    __RegisterClass__o2__Widget__InternalChildrenEditableEditable();
    __RegisterClass__o2__WidgetLayer();
    __RegisterClass__o2__WidgetLayerLayout();
    __RegisterClass__o2__WidgetLayout();
    __RegisterClass__o2__WidgetLayoutData();
    __RegisterClass__o2__WidgetState();
    __RegisterClass__o2__Button();
    __RegisterClass__o2__ContextMenu();
    __RegisterClass__o2__ContextMenuItem();
    __RegisterClass__o2__ContextMenu__Item();
    __RegisterClass__o2__CustomDropDown();
    __RegisterClass__o2__CustomList();
    __RegisterClass__o2__DropDown();
    __RegisterClass__o2__EditBox();
    __RegisterClass__o2__GridLayout();
    __RegisterClass__o2__GridLayoutScrollArea();
    __RegisterClass__o2__HorizontalLayout();
    __RegisterClass__o2__HorizontalProgress();
    __RegisterClass__o2__HorizontalScrollBar();
    __RegisterClass__o2__Image();
    __RegisterClass__o2__Label();
    __RegisterClass__o2__List();
    __RegisterClass__o2__LongList();
    __RegisterClass__o2__MenuPanel();
    __RegisterClass__o2__MenuPanel__Item();
    __RegisterClass__o2__PopupWidget();
    __RegisterClass__o2__ScrollArea();
    __RegisterClass__o2__Spoiler();
    __RegisterClass__o2__Toggle();
    __RegisterClass__o2__Tree();
    __RegisterClass__o2__TreeNode();
    __RegisterClass__o2__VerticalLayout();
    __RegisterClass__o2__VerticalProgress();
    __RegisterClass__o2__VerticalScrollBar();
    __RegisterClass__o2__Window();
    __RegisterClass__o2__DragHandle();
    __RegisterClass__o2__WidgetDragHandle();
    __RegisterClass__o2__SceneEditableObject();
    __RegisterClass__o2__ColorGradient();
    __RegisterClass__o2__ColorGradient__Key();
    __RegisterClass__o2__Curve();
    __RegisterClass__o2__Curve__Key();
    __RegisterClass__o2__Layout();
    __RegisterClass__o2__Spline();
    __RegisterClass__o2__Spline__Key();
    __RegisterClass__o2__Transform();
    __RegisterClass__o2__ISerializable();
    __RegisterClass__o2__ShortcutKeys();
    __RegisterClass__o2__TimeStamp();
}