#include "EditorTestComponent.h"
 
CLASS_META(o2::EditorTestComponent)
{
	BASE_CLASS(o2::Component);

	PUBLIC_FIELD(mInteger).SERIALIZABLE_ATTRIBUTE();
	PUBLIC_FIELD(mFloat).SERIALIZABLE_ATTRIBUTE();
	PUBLIC_FIELD(mString).SERIALIZABLE_ATTRIBUTE();
	PUBLIC_FIELD(mWString).SERIALIZABLE_ATTRIBUTE();
	PUBLIC_FIELD(mBool).SERIALIZABLE_ATTRIBUTE();
	PUBLIC_FIELD(mImageAsset).SERIALIZABLE_ATTRIBUTE();
	PUBLIC_FIELD(mActorAsset).SERIALIZABLE_ATTRIBUTE();
	PUBLIC_FIELD(mDataAsset).SERIALIZABLE_ATTRIBUTE();
	PUBLIC_FIELD(mActor).SERIALIZABLE_ATTRIBUTE();
	PUBLIC_FIELD(mTags).SERIALIZABLE_ATTRIBUTE();
	PUBLIC_FIELD(mLayer).SERIALIZABLE_ATTRIBUTE();
	PUBLIC_FIELD(mComponent).SERIALIZABLE_ATTRIBUTE();
	PUBLIC_FIELD(mImageComponent).SERIALIZABLE_ATTRIBUTE();
	PUBLIC_FIELD(mColor).SERIALIZABLE_ATTRIBUTE();
	PUBLIC_FIELD(mVec2F).SERIALIZABLE_ATTRIBUTE();
	PUBLIC_FIELD(mVec2I).SERIALIZABLE_ATTRIBUTE();
	PUBLIC_FIELD(mVertex).SERIALIZABLE_ATTRIBUTE();
	PUBLIC_FIELD(mRectF).SERIALIZABLE_ATTRIBUTE();
	PUBLIC_FIELD(mRectI).SERIALIZABLE_ATTRIBUTE();
}
END_META;
 